server:
  # 服务端口
  port: 3120

spring:
  profiles:
    active: dev
  # 应用名称
  application:
    name: Grover

# MyBatis-Flex
mybatis-flex:
  global-config:
    print-banner: false
  datasource:
    mysql:
      url: jdbc:mysql://localhost:3306/grover?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
      username: root
      password: root
    sqlite3:
      url: jdbc:sqlite::resource:sqlite/grover.db

# Logging
logging:
  level:
    com.upfor.grover.mapper: debug # MyBatis SQL日志

# 自定义配置
grover:
  author: jioby
