server:
  # 服务端口
  port: 3120

spring:
  # 应用名称
  application:
    name: Grover

  # 数据源
  datasource:
    dynamic: # 多数据源，使用了dynamic-datasource，参考文档：https://baomidou.com/pages/a61e1b
      primary: mysql # 默认数据源
      datasource:
        mysql: # MySQL
          # 数据库驱动
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 数据库连接地址
          url: jdbc:mysql://localhost:3306/grover?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
          # 数据库用户名&密码：
          username: root
          password: root
          # 连接池
          hikari:
            maximum-pool-size: 10
        sqlite3: # Sqlite3
          driver-class-name: org.sqlite.JDBC
          url: jdbc:sqlite::resource:sqlite/grover.db

# MyBatis-Plus
mybatis-plus:
  configuration:
    # 项目采用Logback，MyBatis默认没有支持Logback，但是支持SLF4J，因为Logback实现了SLF4J接口
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  global-config:
    banner: false

# Logging
logging:
  level:
    com.upfor.grover.mapper: debug # MyBatis SQL日志

# 自定义配置
grover:
  author: jioby
